name: Build and Publish P2 Repository

on:
  push:
    # 允许在任何分支推送时触发（包括 feature 分支）
    paths:
      - 'plugins/**'
      - 'features/**'
      - 'pom.xml'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build P2 Repository
      run: |
        mvn clean verify
        
    - name: Prepare P2 Site
      run: |
        mkdir -p p2-site
        cp -r repository/target/repository/* p2-site/
        
        # 创建索引页面
        cat > p2-site/index.html << EOF
        <!DOCTYPE html>
        <html>
        <head>
          <title>RuyiSDK Eclipse Plugins - P2 Repository</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
            h1 { color: #2c3e50; }
            .code { background: #f4f4f4; padding: 10px; border-radius: 5px; }
            .version { color: #27ae60; font-weight: bold; }
          </style>
        </head>
        <body>
          <h1>RuyiSDK Eclipse Plugins</h1>
          <p>P2 更新站点 - 用于 Eclipse IDE 插件安装和更新</p>
          
          <h2>安装方法</h2>
          <ol>
            <li>打开 Eclipse IDE</li>
            <li>Help → Install New Software...</li>
            <li>点击 "Add..." 按钮</li>
            <li>输入以下信息：
              <div class="code">
                Name: RuyiSDK Plugins<br>
                Location: <strong>https://exceed-zk.github.io/ruyisdk-eclipse-plugins/</strong>
              </div>
            </li>
            <li>选择 "RuyiSDK Feature" 并安装</li>
          </ol>
          
          <h2>检查更新</h2>
          <p>Help → Check for Updates</p>
          
          <h2>文档</h2>
          <ul>
            <li><a href="https://github.com/exceed-zk/ruyisdk-eclipse-plugins">GitHub 仓库</a></li>
            <li><a href="https://github.com/exceed-zk/ruyisdk-eclipse-plugins/blob/main/README.md">README</a></li>
          </ul>
          
          <p class="version">最后更新: $(date '+%Y-%m-%d %H:%M:%S')</p>
        </body>
        </html>
        EOF
        
    - name: Deploy to GitHub Pages
      # 只要是推送事件就部署，支持 feature 分支开发测试
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./p2-site
        publish_branch: gh-pages
        force_orphan: true
        
    - name: Upload P2 Repository Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ruyisdk-plugins-p2-repository
        path: repository/target/repository/
        retention-days: 30

