name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.0.5)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
        
    - name: Build P2 Repository
      run: |
        mvn clean verify
        
    - name: Package P2 Repository
      run: |
        cd repository/target
        zip -r ruyisdk-plugins-p2-${{ steps.version.outputs.VERSION }}.zip repository/
        tar -czf ruyisdk-plugins-p2-${{ steps.version.outputs.VERSION }}.tar.gz repository/
        
    - name: Generate Release Notes
      id: release_notes
      run: |
        cat > release_notes.md << 'EOF'
        # RuyiSDK Eclipse Plugins ${{ steps.version.outputs.VERSION }}
        
        ## 包含的插件
        
        - **org.ruyisdk.core** - 核心功能库
        - **org.ruyisdk.devices** - RISC-V 设备管理
        - **org.ruyisdk.intro** - 欢迎界面定制
        - **org.ruyisdk.packages** - 包资源管理器
        - **org.ruyisdk.projectcreator** - 项目创建向导
        - **org.ruyisdk.ruyi** - Ruyi 包管理器集成
        
        ## 安装方法
        
        ### 方法 1：在线安装（推荐）
        
        1. 打开 Eclipse IDE
        2. `Help` → `Install New Software...`
        3. 点击 `Add...` 按钮
        4. 输入：
           - Name: `RuyiSDK Plugins`
           - Location: `https://exceed-zk.github.io/ruyisdk-eclipse-plugins/`
        5. 选择 `RuyiSDK Feature` 并安装
        
        ### 方法 2：离线安装
        
        1. 下载 `ruyisdk-plugins-p2-${{ steps.version.outputs.VERSION }}.zip`
        2. 解压到本地目录
        3. `Help` → `Install New Software...` → `Add...`
        4. Location: `file:///path/to/repository`
        
        ##  系统要求
        
        - Eclipse 2024-9 或更高版本
        - Java 21 或更高版本
        - 支持架构：x86_64, aarch64, riscv64
        
        ##  文档（已移动待修改）
        
        - [安装指南](https://github.com/exceed-zk/ruyisdk-eclipse-plugins/blob/main/安装指南-Linux.md)
        - [构建指南](https://github.com/exceed-zk/ruyisdk-eclipse-plugins/blob/main/RUYISDK_BUILD_GUIDE.md)
        - [兼容性说明](https://github.com/exceed-zk/ruyisdk-eclipse-plugins/blob/main/COMPATIBILITY.md)
        
        ##  问题反馈
        
        如有问题，请在 [GitHub Issues](https://github.com/exceed-zk/ruyisdk-eclipse-plugins/issues) 提交。
        EOF
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: RuyiSDK Plugins ${{ steps.version.outputs.VERSION }}
        body_path: release_notes.md
        files: |
          repository/target/ruyisdk-plugins-p2-${{ steps.version.outputs.VERSION }}.zip
          repository/target/ruyisdk-plugins-p2-${{ steps.version.outputs.VERSION }}.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


